name: Backend CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: three-tier-backend
  ECR_REGISTRY: 717728193465.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository as a pro 
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::717728193465:role/github-actions-s3-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 717728193465.dkr.ecr.us-east-1.amazonaws.com
            docker stop backend || true
            docker rm backend || true
            docker pull 717728193465.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:latest
            docker run -d \
              --name backend \
              -p 3001:3001 \
              --env-file /home/ubuntu/app/backend.env \
              --restart always \
              717728193465.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:latest